[package]
name = "mail"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
iced.workspace = true
mail-engine = { path = "../mail-engine" }
tracing.workspace = true
tracing-subscriber.workspace = true
